<?php
namespace backend\filters;

use yii\base\ActionFilter;
use yii\web\ForbiddenHttpException;

class RbacFilter extends ActionFilter{
	public function beforeAction($action)//操作前执行
	{
		//var_dump(\Yii::$app->user->identity);//exit();
		if (!\Yii::$app->user->can($action->uniqueId)){//检查是否有当前路由的权限
			if (\Yii::$app->user->isGuest){//检查是否登录
				\Yii::$app->session->setFlash('error','请登录');
				return $action->controller->redirect(\Yii::$app->user->loginUrl)->send();
			}
			throw new ForbiddenHttpException('权限不够!');
		}
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
}