<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "address".
 *
 * @property integer $id
 * @property integer $member_id
 * @property string $consignee
 * @property string $prov
 * @property string $city
 * @property string $area
 * @property string $de_address
 * @property string $tel
 * @property integer $is_default
 * @property integer $create_at
 */
class Address extends \yii\db\ActiveRecord
{
	public $remember;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'address';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
        	[['consignee','prov','city','area','de_address','tel'],'required'],
            [['prov','city','area'], 'string'],
            [['consignee'], 'string', 'max' => 50],
            [['de_address', 'tel'], 'string', 'max' => 255],
	        ['remember','string'],//是否设为默认地址
        ];
    }

	public function beforeSave($insert)//重写save前执行的代码
	{//$insert 修改 返回false
			$this->member_id = Yii::$app->user->getId();
			$this->create_at = time();
			if ($this->remember){
				$this->is_default = 1;
				$row = Address::find()->where(['member_id'=>Yii::$app->user->getId(),'is_default'=>1])->one();
				if ($row){
					$row->is_default = 0;
					$row->save(false);
				}
			}
		return parent::beforeSave($insert); // TODO: Change the autogenerated stub
	}

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'member_id' => '用户',
            'consignee' => '收货人',
            'prov' => '省',
            'city' => '市',
            'area' => '区',
            'de_address' => '详细地址',
            'tel' => '手机号码',
            'is_default' => '默认地址',
            'create_at' => '创建时间',
        ];
    }
}
