<?php

namespace frontend\models;

use backend\models\Goods;
use Yii;

/**
 * This is the model class for table "cart".
 *
 * @property integer $id
 * @property integer $goods_id
 * @property integer $amount
 * @property integer $member_id
 */
class Cart extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cart';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['goods_id', 'amount'], 'integer','min'=>1],
            [['goods_id', 'amount'], 'required'],
	        ['goods_id','validateGoods'],//检查对应商品是否存在
        ];
    }
    public function  validateGoods(){
    	$model = Goods::findOne(['id'=>$this->goods_id]);
    	if ($model===null){
    		$this->addError("goods_id","该商品不存在");
    		return false;
	    }
    }

    public function beforeSave($insert)
    {
    	if ($insert){//保存购物车,并且是添加的时候
    		$this->member_id = Yii::$app->user->getId();
	    }
	    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

	/**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'goods_id' => '商品',
            'amount' => '商品数量',
            'member_id' => '用户',
        ];
    }
    //建立和goods表的关系
	public function getGoods(){
    	return $this->hasOne(\backend\models\Goods::className(),['id'=>'goods_id']);
	}
}
